# Generated by Django 2.0.3 on 2018-03-10 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('usr_id', models.IntegerField(primary_key=True, serialize=False)),
                ('fst_name', models.CharField(max_length=65)),
                ('lst_name', models.CharField(max_length=65)),
                ('eml', models.CharField(max_length=50)),
                ('pss', models.CharField(max_length=12)),
            ],
        ),
    ]
